name: Run Linter and Sample Build

on:[push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting and NextJS Build
        run: |
          npm install 
          npm run lint
          npm run build